
services:
###########################
# Setup the Apache container
###########################
    nginx:
        container_name: ${NAME_PROJECT}_httpd
        restart: always
        image: nginx:${VALUE_NGINX_VERSION}
        ports:
            - ${VALUE_NGINX_PORT}:80
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./.docker/containers/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/containers/nginx/conf.d/:/etc/nginx/conf.d
            - ./.dockertmp/log/nginx:/var/log/nginx/
        volumes_from:
            - php

###########################
# Setup the PHP container
###########################
    php:
        container_name: ${NAME_PROJECT}_php
        restart: always
        build: 
            context: ./.docker/images/php/
            args:
                - VALUE_PHP_VERSION=${VALUE_PHP_VERSION}
                - VALUE_XDEBUG_VERSION=${VALUE_XDEBUG_VERSION}
                - VALUE_COMPOSER_VERSION=${VALUE_COMPOSER_VERSION}
                - VALUE_MHSEND_VERSION=${VALUE_MHSENDMAIL_VERSION}
                - VALUE_PHP_UNIT_VERSION=${VALUE_PHP_UNIT_VERSION}
        volumes:
            - ./www/:/usr/local/apache2/www
            - ./.env:/usr/local/apache2/www/${FOLDER_CONFIG}/.env:rw
            - ./config/config_sgbd.php:/usr/local/apache2/www/${FOLDER_CONFIG}/config_sgbd.php:rw
            - ./config/filedotenv.php:/usr/local/apache2/www/${FOLDER_CONFIG}/filedotenv.php:rw
            - ./config/data:/docker-entrypoint-initdata.d:rw
            - ./config/dockercron:/var/docker/cron/dockercron:rw
            - ./.docker/containers/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:ro
            - ./.docker/containers/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./.docker/containers/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./.docker/containers/php/mailhog.ini:/usr/local/etc/php/conf.d/mailhog.ini:ro
            - ./.dockertmp/log/php:/var/log/docker/php:rw
            - ./.dockertmp/log/xdebug:/var/log/docker/xdebug:rw
            - ./.dockertmp/tmp/php:/var/tmp/docker/php:rw
        environment:
            - TZ=${VALUE_TIMEZONES}
            - PHP_FOLDER_DATA=${FOLDER_DATA}
            
###########################
# Setup the Database (postgres) container
###########################
    postgres:
        container_name: ${NAME_PROJECT}_postgres
        restart: always
        image: postgres:${VALUE_POSTGRES_VERSION}
        volumes:
            - ./.dockertmp/postgres_data:/var/lib/postgresql/data
            - ./config/sgbd_data:/docker-entrypoint-initdb.d/:rw
        ports:
            - ${VALUE_POSTGRES_PORT}:5432
        environment:
            - TZ=${VALUE_TIMEZONES}
            - POSTGRES_DB=${SGBD_DATABASE}
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=${SGBD_PASSWORD}
            
###########################
# Setup the PhpMyAdmin container
###########################
    pgadmin:
        container_name: ${NAME_PROJECT}_phppgadmin
        restart: always
        image: neimheadh/phppgadmin:${VALUE_PHPPGADMIN_VERSION}
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=${NAME_PROJECT}_postgres
            - POSTGRES_USER=root
            - POSTGRES_PASS=${SGBD_PASSWORD}
        ports:
            - ${VALUE_PHPPGADMIN_PORT}:80
        depends_on: 
            - postgres
            
###########################
# Setup the mailhog container
###########################
    mailhog:
        build:
            context: .docker/images/mailhog
            args:
                - VALUE_MHOG_VERSION=${VALUE_MAILHOG_VERSION}
        container_name: ${NAME_PROJECT}_mailhog
        restart: always
        volumes:
            - ./.dockertmp/mailhog:/mailhog
            - ./config/email_data:/docker-entrypoint-initdata.d:rw
        environment:
            - MH_STORAGE=maildir
            - MH_MAILDIR_PATH=/mailhog
        ports:
            - ${VALUE_MAILHOG_PORT}:8025
            
